/* DEFINES DO JOGO */

// GameObjects
#define PLAYER_BASE_LIFE 1000
#define FALCON_INITIAL_POS Vec2(200, 400)
#define FALCON_DAMAGE 250
#define FALCON_SPEED_PROPORTION (4/3)
#define LINEAR_SPEED Vec2(0, 300)
#define HIERO_DAMAGE 1
#define HIERO_COOLDOWN 2

